### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by ulmerb** [sisinflab-swot/OWL-API-for-iOS#1]
Hey!
I was trying to install your project, and I got the following error. 

ld: warning: directory not found for option '-L/Users/******/OWL-API-for-iOS/librdf/build/Universal-iOS-Sim'
ld: library not found for -lraptor2
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have installed pkg-config, so I'm not sure how to fix this.
Thanks!

**Comment by IvanoBilenchi** [comment]
Hi!

It looks like the raptor library either isn't being built or the linker cannot find where it is.

Try this: in Xcode, select the "librdf-clean" target and run it. Then select the "OWLAPI-Universal-iOS" target and hit "Product -> Clean". Finally, keep "OWLAPI-Universal-iOS" as your active target and run it.

Make sure your workstation is connected to the internet, as the build scripts need to download the raptor source prior to building it. The build process may take several minutes.

If this doesn't work, I'd need to have a look at the output of the raptor build scripts: in terminal, cd to the librdf/build directory in the OWLAPI source dir, then run:

./start-over.sh
./build.sh

If the build script errors out, it should output meaningful info about why it failed.

**Comment by ulmerb** [comment]
He Ivanko,
Thanks so much, the build.sh seemed to work, and this was its output:
"
->  raptor2-2.0.15.tar.gz
-->  Downloading raptor2-2.0.15.tar.gz (1886 KB)
        1886657  [100.00%]
-->  Mac: i386
--->  Unpacking downloads/raptor2-2.0.15.tar.gz
--->  Configuring build-Mac-i386/raptor2-2.0.15
--->  Building build-Mac-i386/raptor2-2.0.15
--->  Installing build-Mac-i386/raptor2-2.0.15
-->  Mac: x86_64
--->  Unpacking downloads/raptor2-2.0.15.tar.gz
--->  Configuring build-Mac-x86_64/raptor2-2.0.15
--->  Building build-Mac-x86_64/raptor2-2.0.15
--->  Installing build-Mac-x86_64/raptor2-2.0.15
-->  iOS: armv7
--->  Unpacking downloads/raptor2-2.0.15.tar.gz
--->  Configuring build-iOS-armv7/raptor2-2.0.15
--->  Building build-iOS-armv7/raptor2-2.0.15
--->  Installing build-iOS-armv7/raptor2-2.0.15
-->  iOS: armv7s
--->  Unpacking downloads/raptor2-2.0.15.tar.gz
--->  Configuring build-iOS-armv7s/raptor2-2.0.15
--->  Building build-iOS-armv7s/raptor2-2.0.15
--->  Installing build-iOS-armv7s/raptor2-2.0.15
-->  iOS: arm64
--->  Unpacking downloads/raptor2-2.0.15.tar.gz
--->  Configuring build-iOS-arm64/raptor2-2.0.15
--->  Building build-iOS-arm64/raptor2-2.0.15
--->  Installing build-iOS-arm64/raptor2-2.0.15
-->  Sim: i386
--->  Unpacking downloads/raptor2-2.0.15.tar.gz
--->  Configuring build-Sim-i386/raptor2-2.0.15
--->  Building build-Sim-i386/raptor2-2.0.15
--->  Installing build-Sim-i386/raptor2-2.0.15
-->  Sim: x86_64
--->  Unpacking downloads/raptor2-2.0.15.tar.gz
--->  Configuring build-Sim-x86_64/raptor2-2.0.15
--->  Building build-Sim-x86_64/raptor2-2.0.15
--->  Installing build-Sim-x86_64/raptor2-2.0.15
->  Creating universal libraries"

I think my issue was one of the folders containing my project had a space in it, and the build script relied upon not having spaces in the path. The build.sh script was verbose about this though, and I changed the path. Thanks so much again for your help!

**Comment by IvanoBilenchi** [comment]
Thanks for the follow-up, I was actually unaware of this (and indeed my build dir doesn't have any whitespaces). I should probably look into ways to improve on that, or mention it in the docs.

Either way, glad you solved this and good luck on your project!
